version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    conmands:
      - 'cd Reimbursement-API-1'
      - 'npm install'
artifacts:
  files:
    - '**/*'
  base-directory: 'Reimbursement-API-1'